[target.thumbv7m-none-eabi]
runner = 'probe-rs run --chip STM32F401RCT6'
rustflags = [
  "-C", "link-arg=-Tlink.x",
  #"-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7m-none-eabi"

[env]
DEFMT_LOG = "info"